nav:
  - Home: index.md
  - Quick Start: quickstart/getting_started.md
  - Application for Login and Resources:
    - Overview: application/overview.md
    - Terms of Use: application/terms_of_use.md
    - Request for Resources: application/request_for_resources.md
    - Project Request Form Jards: application/project_request_form.md
    - Project Management: application/project_management.md
    - Acknowledgement: application/acknowledgement.md
  - Access to ZIH Systems:
    - Overview: access/overview.md
    - Connecting with SSH: 
      - Connecting via Terminal (Linux, Mac, Windows): access/ssh_login.md
      - Connecting with MobaXterm (Windows): access/ssh_mobaxterm.md
      - Connecting with PuTTY (Windows): access/ssh_putty.md
    - Desktop Cloud Visualization (DCV): access/desktop_cloud_visualization.md
    - Graphical Applications with WebVNC: access/graphical_applications_with_webvnc.md
    - JupyterHub:
      - JupyterHub: access/jupyterhub.md
      - Custom Environments for JupyterHub: access/jupyterhub_custom_environments.md
      - JupyterHub for Teaching: access/jupyterhub_for_teaching.md
      - JupyterHub Teaching Example: access/jupyterhub_teaching_example.md
    - Key Fingerprints: access/key_fingerprints.md  
    - Security Restrictions: access/security_restrictions.md
  - Data Transfer:
    - Overview: data_transfer/overview.md
    - Transfer Data Inside ZIH Systems with Datamover: data_transfer/datamover.md
    - Transfer Data to/from ZIH Systems via Export Nodes: data_transfer/export_nodes.md
    - Transfer Data between ZIH Systems and Object Storage (S3): data_transfer/object_storage.md
  - Data Life Cycle Management:
    - Overview: data_lifecycle/overview.md
    - Filesystems:
      - Overview: data_lifecycle/file_systems.md
      - Permanent Filesystems: data_lifecycle/permanent.md
      - Lustre: data_lifecycle/lustre.md
      - BeeGFS: data_lifecycle/beegfs.md
      - Warm Archive: data_lifecycle/warm_archive.md
      - Intermediate Archive: data_lifecycle/intermediate_archive.md
    - Workspaces: data_lifecycle/workspaces.md
    - Long-Term Preservation of Research Data: data_lifecycle/longterm_preservation.md
    - Sharing Data: data_lifecycle/data_sharing.md
  - User Environment:
    - Overview: software/overview.md
    - Environment Modules: software/modules.md
    - Private Modules: software/private_modules.md
    - Software Installation with EasyBuild: software/custom_easy_build_environment.md
    - Python Virtual Environments: software/python_virtual_environments.md
    - ZSH as Alternative Shell: software/zsh.md
  - Applications and Software:
    - Containers:
      - Singularity: software/containers.md
      - Singularity Recipes and Hints: software/singularity_recipe_hints.md
      - Singularity for Power9 Architecture: software/singularity_power9.md
      - Virtual Machines: software/virtual_machines.md
      - GPU-accelerated Containers for Deep Learning (NGC Containers): software/ngc_containers.md
    - External Licenses: software/licenses.md
    - Computational Fluid Dynamics (CFD): software/cfd.md
    - Mathematics Applications: software/mathematics.md
    - Nanoscale Simulations: software/nanoscale_simulations.md
    - FEM Software: software/fem_software.md
    - Visualization: software/visualization.md
    - Data Analytics:
      - Overview: software/data_analytics.md
      - Data Analytics with R: software/data_analytics_with_r.md
      - Data Analytics with RStudio: software/data_analytics_with_rstudio.md
      - Data Analytics with Python: software/data_analytics_with_python.md
      - Big Data Analytics: software/big_data_frameworks.md
    - Machine Learning:
      - Overview: software/machine_learning.md
      - Neural Networks with TensorFlow: software/tensorflow.md
      - Inspect Model Training with TensorBoard: software/tensorboard.md
      - Neural Networks with PyTorch: software/pytorch.md
      - Distributed Training: software/distributed_training.md
      - Hyperparameter Optimization (OmniOpt): software/hyperparameter_optimization.md
      - Machine Learning with PowerAI: software/power_ai.md
    - Virtual Desktops: software/virtual_desktops.md
  - Software Development and Tools:
    - Overview: software/software_development_overview.md
    - Building Software:
      - Overview: software/building_software.md
      - Compilers and Flags: software/compilers.md
      - GPU Programming: software/gpu_programming.md
      - Mathematics Libraries: software/math_libraries.md
      - Known Issues when Using MPI: jobs_and_resources/mpi_issues.md
      - Debugging: software/debuggers.md
    - Performance Engineering Tools:
      - Overview: software/performance_engineering_overview.md
      - Record Course of Events with lo2s: software/lo2s.md
      - Check MPI Correctness with MUST: software/mpi_usage_error_detection.md
      - Read CPU Performance Counters with PAPI: software/papi.md
      - Produce Performance Overview with Perf: software/perf_tools.md
      - Track Slurm Jobs with PIKA: software/pika.md
      - Record Course of Events with Score-P: software/scorep.md
      - Study Course of Events with Vampir: software/vampir.md
      - Measure Energy Consumption: software/energy_measurement.md
      - Compare System Performance with SPEChpc: software/spec.md
    - Utilities: software/utilities.md
  - HPC Resources and Jobs:
    - Overview: jobs_and_resources/overview.md
    - HPC Resources:
      - Overview: jobs_and_resources/hardware_overview.md
      - Architecture 2023: jobs_and_resources/architecture_2023.md
      - AMD Rome Nodes: jobs_and_resources/rome_nodes.md
      - NVMe Storage: jobs_and_resources/nvme_storage.md
      - Alpha Centauri: jobs_and_resources/alpha_centauri.md
      - HPE Superdome Flex: jobs_and_resources/sd_flex.md
      - NVIDIA Arm HPC Developer Kit: jobs_and_resources/arm_hpc_devkit.md
    - Running Jobs:
      - Batch System Slurm: jobs_and_resources/slurm.md
      - Job Examples: jobs_and_resources/slurm_examples.md
      - Partitions and Limits: jobs_and_resources/partitions_and_limits.md
      - Slurm Job File Generator: jobs_and_resources/slurm_generator.md
      - Checkpoint/Restart: jobs_and_resources/checkpoint_restart.md
      - Binding and Distribution of Tasks: jobs_and_resources/binding_and_distribution_of_tasks.md
  - User Support: support/support.md
  - Archive:
    - Overview: archive/overview.md
    - Bio Informatics: archive/bioinformatics.md
    - CXFS End of Support: archive/cxfs_end_of_support.md
    - Load Leveler: archive/load_leveler.md
    - Jobs without InfiniBand: archive/no_ib_jobs.md
    - Migration towards Phase 2: archive/phase2_migration.md
    - Platform LSF: archive/platform_lsf.md
    - BeeGFS Filesystem on Demand: archive/beegfs_on_demand.md
    - Jupyter Installation: archive/install_jupyter.md
    - Job Profiling: archive/slurm_profiling.md
    - Switched-Off Systems:
      - Overview 2022: archive/hardware_overview_2022.md
      - Overview: archive/systems_switched_off.md
      - Migration From Deimos to Atlas: archive/migrate_to_atlas.md
      - System Altix: archive/system_altix.md
      - System Atlas: archive/system_atlas.md
      - System Deimos: archive/system_deimos.md
      - System Phobos: archive/system_phobos.md
      - System Titan: archive/system_titan.md
      - System Triton: archive/system_triton.md
      - System Venus: archive/system_venus.md
      - KNL Nodes: archive/knl_nodes.md
    - SCS5 Migration Hints: archive/scs5_software.md
    - UNICORE Rest API: archive/unicore_rest_api.md
    - VampirTrace: archive/vampirtrace.md
    - Windows Batchjobs: archive/windows_batch.md
  - Contribute to Documentation:
    - How-To Contribute: contrib/howto_contribute.md
    - Content Rules: contrib/content_rules.md
    - Contribute via Browser: contrib/contribute_browser.md
    - Contribute via Local Clone: contrib/contribute_container.md
    
# Project Information

site_name: ZIH HPC Compendium
site_description: ZIH HPC Compendium
site_author: ZIH Team
site_dir: public
site_url: https://doc.zih.tu-dresden.de/

# uncomment next 3 lines if link to repo should not be displayed in the navbar

repo_name: GitLab hpc-compendium
repo_url: https://gitlab.hrz.tu-chemnitz.de/zih/hpcsupport/hpc-compendium
edit_uri: blob/main/doc.zih.tu-dresden.de/docs/

# Configuration

# strict: true

theme:

  # basetheme

  name: material

  # disable fonts being loaded from google fonts

  font: false
  language: en

  # dir containing all customizations

  custom_dir: tud_theme
  favicon: assets/images/Logo_klein.png

  # logo in header and footer

  logo: assets/images/TUD_Logo_weiss_57.png
  second_logo: assets/images/zih_weiss.png
  features:
    - navigation.instant
    - search.highlight
    
# extends base css/js
extra_css:

  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/mermaid.min.js

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight
    - toc:
        permalink: True
    - attr_list
    - footnotes
    - pymdownx.tabbed:
        alternate_style: True

          #  - mkdocs-video

plugins:
  - search
  - markdown-caption
  # https://github.com/manuzhang/mkdocs-htmlproofer-plugin
  - htmlproofer:
      # True by default
      # Toggle via env. var. ENABLED_HTMLPROOFER=false
      enabled: !ENV [ENABLED_HTMLPROOFER, True]
      # Check URLs before serving. Build fails in case of bad URLs.
      raise_error: True
      # Ignore errors
      #raise_error_excludes:
      #  504: ['https://www.mkdocs.org/']
      # Toggle validating external URLs
      validate_external_urls: False
      # Validate the entire rendered template, slow!
      validate_rendered_template: True
  - mkdocs-video:
      is_video: True

# Enable cross-page anchor validation
# https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
# True by default. But: explicit is better than implicit.
use_directory_urls: True

extra:
  tud_homepage: https://tu-dresden.de
  tud_name: "TU Dresden"
  # second logo
  zih_homepage: https://tu-dresden.de/zih
  zih_name: "center for information services and high performance computing (ZIH)"
  hpcsupport_mail: hpcsupport@zih.tu-dresden.de

  # links in footer

  footer:
    - link: /legal_notice
      name: "Legal Notice / Impressum"
    - link: /accessibility
      name: "Accessibility / Barrierefreiheit"
    - link: /data_protection_declaration
      name: "Data Protection Declaration / Datenschutzerkl√§rung"
    - link: https://tu-dresden.de/zertifikate
      name: "Certificates"

